from PySide6.QtCore import Qt, QPointF
from PySide6.QtGui import QCursor, QMouseEvent, QKeyEvent


class BaseTool:
    def __init__(self, view, document):
        self.view = view
        self.document = document

    def activate(self): ...
    def deactivate(self): ...
    def cursor(self) -> QCursor:
        return QCursor(Qt.CursorShape.ArrowCursor)

    def mouse_press(self, event: QMouseEvent, scene_pos: QPointF): ...
    def mouse_move(self, event: QMouseEvent, scene_pos: QPointF): ...
    def mouse_release(self, event: QMouseEvent, scene_pos: QPointF): ...
    def key_press(self, event: QKeyEvent): ...
